[Server]
Host = "0.0.0.0"
Port =9000
Debug = true
LogLevel = "Info"
shutdownTimeout = 3
Pid = "/apps/crawl-demo/run.pid"

[DataBase]
Driver = "mysql"
Host = "127.0.0.1"
Port = 3306
Username = "root"
Password = "2222"
Name = "crawl"

[Fetcher]
Qps =2


